server:
  port: 8848
  tomcat:
    basedir: logs

db:
  num: 1
  user: ${MYSQL-NACOS-USER:root}
  password: ${MYSQL-NACOS-PWD:12345678}
  url:
    0: jdbc:mysql://${MYSQL-NACOS-HOST:xcloud.nacos.mysql}:${MYSQL-NACOS-PORT:3306}/${MYSQL-NACOS-DB:xcloud_config}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true


nacos:
  istio:
    mcp:
      server:
        enabled: false
  core:
    auth:
      default:
        token:
          expire:
            seconds: 18000
      caching:
        enabled: true
      enabled: false
      system.type: nacos
      default.token.secret.key: SecretKey012345678901234567890123456789012345678901234567890123456789
  security:
    ignore:
      urls: /,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**

spring:
  datasource:
    platform: mysql
  security:
    enabled: true


useAddressServer: true

management:
  metrics:
    export:
      influx:
        enabled: false
      elastic:
        enabled: false
